name: faiss_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - faiss-cpu
  - pip
  - pip:
    - langchain
    - langchain-openai
    - langchain-community
    - langchain-text-splitters
    - langchain-core
    - openai
    - streamlit
    - python-dotenv
